[project]
name = "langgraph-finance-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "s100422", email = "tnwls9793@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "agentevals>=0.0.9",
    "google-genai>=2.24.0",
    "ipykernel>=7.4.0",
    "langchain>=1.4.2",
    "langchain-google-genai>=4.4.0",
    "langgraph>=1.2.12",
    "langsmith>=0.14.0",
    "openevals>=0.2.0",
    "python-dotenv>=1.2.3",
]

[project.scripts]
langgraph-finance-agent = "langgraph_finance_agent:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
